# Generated by Django 6.0.6 on 2026-07-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('staff_number', models.CharField(blank=True, default='', max_length=30)),
                ('department_unit', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('shares_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('welfare_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('compulsory_savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['membership_id'],
                'indexes': [models.Index(fields=['status'], name='members_mem_status_734de0_idx')],
            },
        ),
    ]
