import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Card } from "../../components/Card";
import { Button } from "../../components/Button";
import { Select } from "../../components/Select";
import { TextField } from "../../components/TextField";
import { Avatar } from "../../components/Avatar";
import { ProgressBar } from "../../components/ProgressBar";
import { DataTable, type Column } from "../../components/Table";
import { Badge } from "../../components/Badge";
import { Icon } from "../../components/Icon";
import { useToast } from "../../components/Toast";
import { formatDateTime } from "../../lib/format";
import { fetchReportJobs, generateReport, reportTypes } from "./api";
import { lookupMemberByMembershipId } from "../shared/memberLookup";
import type { MockReportJob } from "../../mocks/reports";

const reportTypeLabels = Object.fromEntries(reportTypes.map((t) => [t.value, t.label]));
const formatOptions = [
  { value: "PDF", label: "PDF" },
  { value: "EXCEL", label: "Excel" },
];

export function ReportsAdminPage() {
  const [reportType, setReportType] = useState(reportTypes[0].value);
  const [format, setFormat] = useState<"PDF" | "EXCEL">("PDF");
  const [period, setPeriod] = useState("");
  const [membershipId, setMembershipId] = useState("");
  const [jobState, setJobState] = useState<"idle" | "running" | "done">("idle");
  const [progress, setProgress] = useState(0);
  const toast = useToast();
  const queryClient = useQueryClient();

  const isMemberStatement = reportType === "MEMBER_STATEMENT";
  const memberLookup = isMemberStatement ? lookupMemberByMembershipId(membershipId) : {};

  const { data: jobs, isLoading } = useQuery({
    queryKey: ["reports", "jobs"],
    queryFn: fetchReportJobs,
  });

  const mutation = useMutation({
    mutationFn: generateReport,
    onSuccess: (job) => {
      toast.show({
        tone: "success",
        title: "Report generated",
        description: `${reportTypeLabels[job.report_type]} (${job.format}) for ${job.period_label}.`,
      });
      queryClient.invalidateQueries({ queryKey: ["reports"] });
    },
  });

  function startGenerating() {
    if (!period.trim()) {
      toast.show({
        tone: "error",
        title: "Enter a period",
        description: 'e.g. "July 2026" or "Q3 2026".',
      });
      return;
    }
    if (isMemberStatement && !memberLookup.member) {
      toast.show({
        tone: "error",
        title: "Select a member",
        description: "Enter a valid membership ID to generate their statement.",
      });
      return;
    }
    setJobState("running");
    setProgress(0);
    const interval = setInterval(() => {
      setProgress((p) => Math.min(p + Math.random() * 22, 92));
    }, 200);
    mutation.mutate(
      {
        reportType,
        format,
        periodLabel: period,
        scope: isMemberStatement ? "MEMBER" : "COOPERATIVE",
        generatedBy: "Current admin",
        memberId: memberLookup.member?.id,
      },
      {
        onSettled: () => {
          clearInterval(interval);
          setProgress(100);
          setJobState("done");
          if (isMemberStatement) setMembershipId("");
        },
      },
    );
  }

  const columns: Column<MockReportJob>[] = [
    { key: "type", header: "Report", render: (j) => reportTypeLabels[j.report_type] ?? j.report_type },
    { key: "period", header: "Period", render: (j) => j.period_label },
    {
      key: "format",
      header: "Format",
      render: (j) => <Badge tone={j.format === "PDF" ? "brick" : "pine"}>{j.format}</Badge>,
    },
    { key: "by", header: "Generated by", render: (j) => j.generated_by, className: "hidden md:table-cell" },
    { key: "date", header: "Generated", render: (j) => formatDateTime(j.generated_at) },
    {
      key: "download",
      header: "",
      className: "text-right",
      render: () => (
        <Button
          size="sm"
          variant="ghost"
          onClick={() =>
            toast.show({
              tone: "info",
              title: "Download started",
              description: "This is a mock — no real file is generated yet.",
            })
          }
        >
          <Icon name="download" className="h-4 w-4" /> Download
        </Button>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="text-sm text-sand-500 dark:text-sand-400">
          Generate financial statements and member reports.
        </p>
      </div>

      <Card className="p-6">
        <p className="mb-4 text-sm font-medium text-sand-500 dark:text-sand-400">
          Generate a report
        </p>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
          <Select
            label="Report type"
            options={reportTypes}
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
          />
          <TextField
            label="Period"
            placeholder="e.g. July 2026"
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
          />
          <Select
            label="Format"
            options={formatOptions}
            value={format}
            onChange={(e) => setFormat(e.target.value as "PDF" | "EXCEL")}
          />
        </div>

        {isMemberStatement && (
          <div className="mt-4 flex flex-col gap-2">
            <TextField
              label="Member membership ID"
              placeholder="e.g. NDU-0007"
              value={membershipId}
              onChange={(e) => setMembershipId(e.target.value)}
              error={memberLookup.error}
            />
            {memberLookup.member && (
              <div className="flex items-center gap-2.5 rounded-lg border border-pine-200 bg-pine-50 px-3 py-2 dark:border-pine-800 dark:bg-pine-950/30">
                <Avatar
                  firstName={memberLookup.member.first_name}
                  lastName={memberLookup.member.last_name}
                  size="sm"
                />
                <p className="text-sm font-medium text-pine-800 dark:text-pine-200">
                  {memberLookup.member.first_name} {memberLookup.member.last_name}
                </p>
                <Icon name="check" className="ml-auto h-4 w-4 text-pine-600 dark:text-pine-400" />
              </div>
            )}
          </div>
        )}

        {jobState !== "idle" && (
          <div className="mt-4 flex flex-col gap-2">
            <ProgressBar value={progress} max={100} tone={jobState === "done" ? "pine" : "gold"} />
            <p className="text-xs text-sand-500 dark:text-sand-400">
              {jobState === "done" ? "Report ready." : "Generating report…"}
            </p>
          </div>
        )}

        <div className="mt-4 flex justify-end">
          <Button onClick={startGenerating} loading={jobState === "running"}>
            <Icon name="file" className="h-4 w-4" /> Generate report
          </Button>
        </div>
      </Card>

      <div>
        <p className="mb-3 text-sm font-medium text-sand-500 dark:text-sand-400">
          Previously generated
        </p>
        <DataTable
          columns={columns}
          rows={jobs ?? []}
          rowKey={(j) => j.id}
          isLoading={isLoading}
          emptyState={{
            title: "No reports yet",
            description: "Generated reports will appear here.",
          }}
        />
      </div>
    </div>
  );
}
